package com.pacytology.pcs;

/*
		A basic implementation of the JDialog class.
*/

import java.awt.*;
import javax.swing.*;
import java.sql.*;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.util.Vector;
import java.io.*;
import java.util.Properties;
import java.awt.Window;
import java.awt.Toolkit;

public class FaxLetterDialog extends javax.swing.JDialog
{
    private int genericLetterCount = 0;
    private int diagnosisLetterCount = 0;
    private int nmnLetterCount = 0;
    private Vector fileNames = new Vector();
    
	public FaxLetterDialog()
	{
		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parse your Java file into its visual environment.
		//{{INIT_CONTROLS
		setTitle("Fax Letters");
		setResizable(false);
		setModal(true);
		getContentPane().setLayout(null);
		getContentPane().setFont(new Font("Dialog", Font.BOLD, 12));
		setSize(258,133);
		setVisible(false);
		genericLtr.setText("Missing Information");
		getContentPane().add(genericLtr);
		genericLtr.setBounds(20,20,240,20);
		diagnosisLtr.setText("Medicare (Low, High, or Diagnostic)");
		getContentPane().add(diagnosisLtr);
		diagnosisLtr.setBounds(20,40,240,20);
		nmnLtr.setText("Not Medically Necessary");
		getContentPane().add(nmnLtr);
		nmnLtr.setBounds(20,60,240,20);
		printButton.setText("Print Letters");
		getContentPane().add(printButton);
		printButton.setBounds(20,96,136,24);
		//}}
		
		getLetterCounts();
	
		//{{REGISTER_LISTENERS
		SymAction lSymAction = new SymAction();
		printButton.addActionListener(lSymAction);
		//}}
	}

	public FaxLetterDialog(String sTitle)
	{
		this();
		setTitle(sTitle);
	}

	public void setVisible(boolean b)
	{
		if (b) setLocation(50, 50);
		super.setVisible(b);
	}

	static public void main(String args[])
	{
		(new FaxLetterDialog()).setVisible(true);
	}

	public void addNotify()
	{
		// Record the size of the window prior to calling parents addNotify.
		Dimension size = getSize();

		super.addNotify();

		if (frameSizeAdjusted)
			return;
		frameSizeAdjusted = true;

		// Adjust size of frame according to the insets
		Insets insets = getInsets();
		setSize(insets.left + insets.right + size.width, insets.top + insets.bottom + size.height);
	}

	// Used by addNotify
	boolean frameSizeAdjusted = false;

	//{{DECLARE_CONTROLS
	javax.swing.JCheckBox genericLtr = new javax.swing.JCheckBox();
	javax.swing.JCheckBox diagnosisLtr = new javax.swing.JCheckBox();
	javax.swing.JCheckBox nmnLtr = new javax.swing.JCheckBox();
	javax.swing.JButton printButton = new javax.swing.JButton();
	//}}
	
	
	private void getLetterCounts()
	{
        ResultSet rs = null;
        Statement stmt = null;
        String SQL = 
            "SELECT letter_type,COUNT(letter_type) \n"+
            "FROM pcs.fax_letters \n"+
            "WHERE in_queue = 1 \n"+
            "GROUP BY letter_type \n";
        try {
            stmt = DbConnection.process().createStatement();
            rs = stmt.executeQuery(SQL);
            String ltrType = null;
            int rcnt = 0;
            while (rs.next()) {
                ltrType=rs.getString(1);
                rcnt=rs.getInt(2);
                if (ltrType.equals("GENERIC"))
                    genericLetterCount=rcnt;
                else if (ltrType.equals("DIAGNOSIS"))
                    diagnosisLetterCount=rcnt;
                else if (ltrType.equals("NMN"))
                    nmnLetterCount=rcnt;
            }    
            rs.close(); stmt.close();
        }
        catch (Exception e) {}
    }

	class SymAction implements java.awt.event.ActionListener
	{
		public void actionPerformed(java.awt.event.ActionEvent event)
		{
			Object object = event.getSource();
			if (object == printButton)
				printButton_actionPerformed(event);
		}
	}

	void printButton_actionPerformed(java.awt.event.ActionEvent event)
	{
		if (!checkPrint()) {
		    Utils.createErrMsg("NO LETTERS SELECTED TO PRINT");
		}
	}
	
	private boolean checkPrint()
	{
	    boolean canPrint = false;
	    if (genericLtr.isSelected()) {
	        canPrint=true;
	        if (genericLetterCount>0) fileNames.addElement("generic.ltr");
	        else fileNames.addElement("generic.old");
	    }
	    if (diagnosisLtr.isSelected()) {
	        canPrint=true;
	        if (diagnosisLetterCount>0) fileNames.addElement("diag.ltr");
	        else fileNames.addElement("diag.old");
	    }
	    if (nmnLtr.isSelected()) {
	        canPrint=true;
	        if (nmnLetterCount>0) fileNames.addElement("medicare.ltr");
	        else fileNames.addElement("medicare.old");
	    }
	    return (canPrint);
	}
	/*
	private void printLetters()
	{
	    PrintJob pjob;
	    Properties p = new java.util.Properties();
	    Graphics pgraphics;
	    String name = new String("Fax Letters");
	    pjob=getToolkit().getPrintJob(this,name,p);
	    if (pjob!=null) {}
	    pjob.end();
	}
	*/
	private void printLetterFile(
	String filePath, String fileName, boolean forcePage)
	{
        File f;
        File f2;
        FileInputStream fIN;
        FileOutputStream fOUT;
        f = new File(filePath,fileName);
        f2 = new File("c:\\","lpt2");
        if (f.exists()) {
            long fLen = f.length();
            if (fLen>0) { 
                try {
                    fIN = new FileInputStream(f);
                    fOUT = new FileOutputStream(f2);
                    //setPrinterCode(fOUT,INIT);
                    for (int k=0; k<fLen-2; k++) {
                    //for (;;) {
                        int x = fIN.read();
                        if (x==-1) break;
                        fOUT.write(x);
                    }
                    if (forcePage) fOUT.write(12);
                    fIN.close();
                    fOUT.close();
                }
                catch (Exception e) { System.out.println(e); }
            }	    
        }
		else Utils.createErrMsg("Cannot locate report: "+fileName); 
	}
	
	
}
