package com.pacytology.pcs;

/*
    PENNSYLVANIA CYTOLOGY SERVICES
    LABORATORY INFORMATION SYSTEM V1.0
    Copyright (C) 2001 by John Cardella
    All Rights Reserved
    
    File:       RecvDateDialog.java
    Created By: John Cardella, Software Engineer
    
    Function:   Dialog box for entering the receive
                date for a lab.
    
    MODIFICATIONS ----------------------------------
    Date/Staff      Description:
*/

import java.awt.*;
import javax.swing.*;

public class RecvDateDialog extends javax.swing.JDialog
{
    String recvDate;
    LabRec labRec;
    
	public RecvDateDialog(Frame parent)
	{
		super(parent);
		
		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parse your Java file into its visual environment.
		//{{INIT_CONTROLS
		setTitle("Date Received");
		setResizable(false);
		setModal(true);
		getContentPane().setLayout(null);
		setSize(212,96);
		setVisible(false);
		labNumLbl.setRequestFocusEnabled(false);
		labNumLbl.setText("Lab Number");
		getContentPane().add(labNumLbl);
		labNumLbl.setForeground(java.awt.Color.black);
		labNumLbl.setFont(new Font("Dialog", Font.BOLD, 12));
		labNumLbl.setBounds(20,18,180,12);
		JLabel1.setRequestFocusEnabled(false);
		JLabel1.setText("MUST Enter receive date!");
		getContentPane().add(JLabel1);
		JLabel1.setForeground(java.awt.Color.black);
		JLabel1.setFont(new Font("Dialog", Font.BOLD, 12));
		JLabel1.setBounds(20,34,180,12);
		JLabel2.setRequestFocusEnabled(false);
		JLabel2.setText("Date Received:");
		getContentPane().add(JLabel2);
		JLabel2.setForeground(java.awt.Color.black);
		JLabel2.setFont(new Font("Dialog", Font.BOLD, 12));
		JLabel2.setBounds(20,62,100,12);
		dateReceived.setEnabled(false);
		getContentPane().add(dateReceived);
		dateReceived.setFont(new Font("SansSerif", Font.PLAIN, 12));
		dateReceived.setBounds(112,60,76,20);
		//}}
	
		//{{REGISTER_LISTENERS
		SymKey aSymKey = new SymKey();
		this.addKeyListener(aSymKey);
		dateReceived.addKeyListener(aSymKey);
		SymWindow aSymWindow = new SymWindow();
		this.addWindowListener(aSymWindow);
		//}}
	}

	public RecvDateDialog()
	{
		this((Frame)null);
	}

	public RecvDateDialog(String labNum, LabRec labRec)
	{
		this();
		this.labRec=labRec;
		this.labNumLbl.setText("Lab Number "+labNum);
		if (!Utils.isNull(this.labRec.receive_date))
		    dateReceived.setText(Utils.addDateMask(this.labRec.receive_date));
	}
	
	public void setVisible(boolean b)
	{
		if (b) setLocation(100,70);
		super.setVisible(b);
	}

	static public void main(String args[])
	{
		(new RecvDateDialog()).setVisible(true);
	}

	public void addNotify()
	{
		// Record the size of the window prior to calling parents addNotify.
		Dimension size = getSize();

		super.addNotify();

		if (frameSizeAdjusted)
			return;
		frameSizeAdjusted = true;

		// Adjust size of frame according to the insets
		Insets insets = getInsets();
		setSize(insets.left + insets.right + size.width, insets.top + insets.bottom + size.height);
	}

	// Used by addNotify
	boolean frameSizeAdjusted = false;

	//{{DECLARE_CONTROLS
	javax.swing.JLabel labNumLbl = new javax.swing.JLabel();
	javax.swing.JLabel JLabel1 = new javax.swing.JLabel();
	javax.swing.JLabel JLabel2 = new javax.swing.JLabel();
	javax.swing.JTextField dateReceived = new javax.swing.JTextField();
	//}}


	class SymKey extends java.awt.event.KeyAdapter
	{
		public void keyTyped(java.awt.event.KeyEvent event)
		{
			Object object = event.getSource();
			if (object == dateReceived)
				dateReceived_keyTyped(event);
		}

		public void keyPressed(java.awt.event.KeyEvent event)
		{
			Object object = event.getSource();
			if (object == RecvDateDialog.this)
				RecvDateDialog_keyPressed(event);
			else if (object == dateReceived)
				dateReceived_keyPressed(event);
		}
	}

	void RecvDateDialog_keyPressed(java.awt.event.KeyEvent event)
	{
		// to do: code goes here.
	}

	void dateReceived_keyPressed(java.awt.event.KeyEvent event)
	{
		if (event.getKeyCode()==event.VK_ENTER) {
		    if (Utils.required(dateReceived,"Date Received")) {
		        if (Utils.dateVerify(dateReceived)) {
		            labRec.receive_date=Utils.stripDateMask(dateReceived.getText());
		            this.dispose();
		        }
		    }
		}
	}

	void dateReceived_keyTyped(java.awt.event.KeyEvent event)
	{
        Utils.buildDateMask(event);
	}
	

	class SymWindow extends java.awt.event.WindowAdapter
	{
		public void windowOpened(java.awt.event.WindowEvent event)
		{
			Object object = event.getSource();
			if (object == RecvDateDialog.this)
				RecvDateDialog_windowOpened(event);
		}
	}

	void RecvDateDialog_windowOpened(java.awt.event.WindowEvent event)
	{
		dateReceived.setEnabled(true);
		dateReceived.requestFocus();
	}
	
}
