package com.pacytology.pcs;

/*

		A basic implementation of the JFrame class.
*/

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Insets;
import java.awt.PrintJob;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Properties;
import java.util.Vector;

import javax.swing.AbstractAction;
import javax.swing.JLabel;
import javax.swing.JRootPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;

import com.pacytology.pcs.actions.PcsActionMap;
import com.pacytology.pcs.ui.PcsFrame;
import com.pacytology.pcs.ui.Square;

public class TissueCodeForm extends PcsFrame
{
    public Login dbLogin;
    Vector resultCodeVect;
    /*
    final int IDLE=100;
    final int QUERY=101;
    final int ADD=102;
    final int UPDATE=103;
    final int DELETE=104;
    */
    public int currMode=Lab.IDLE;    
    final int CODES_PER_SCREEN=15;
    public int rowID=1;
    public FunctionKeyControl fKeys = new FunctionKeyControl();
    public TissueCodeTableData dData;
    public JTable tissueCodeTable;
    public JTableHeader header;
    public JScrollPane rCodeScrollPane;
    private String oldDescription;
    private boolean descriptionChanged = false;
    private int x,y;
    private int lineCount, pageNumber;

	public TissueCodeForm()
	{
		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parse your Java file into its visual environment.
		//{{INIT_CONTROLS
		setTitle("Tissue Codes");
		getContentPane().setLayout(null);
		setSize(702,404);
		setVisible(false);
		getContentPane().add(F1sq);
		F1sq.setBounds(35,6,20,20);
		F1lbl.setRequestFocusEnabled(false);
		F1lbl.setText("F1");
		getContentPane().add(F1lbl);
		F1lbl.setForeground(java.awt.Color.black);
		F1lbl.setFont(new Font("SansSerif", Font.PLAIN, 10));
		F1lbl.setBounds(39,6,20,20);
		getContentPane().add(F2sq);
		F2sq.setBounds(97,6,20,20);
		F2lbl.setRequestFocusEnabled(false);
		F2lbl.setText("F2");
		getContentPane().add(F2lbl);
		F2lbl.setForeground(java.awt.Color.black);
		F2lbl.setFont(new Font("SansSerif", Font.PLAIN, 10));
		F2lbl.setBounds(101,6,20,20);
		getContentPane().add(F3sq);
		F3sq.setBounds(159,6,20,20);
		F3lbl.setRequestFocusEnabled(false);
		F3lbl.setText("F3");
		getContentPane().add(F3lbl);
		F3lbl.setForeground(java.awt.Color.black);
		F3lbl.setFont(new Font("SansSerif", Font.PLAIN, 10));
		F3lbl.setBounds(163,6,20,20);
		getContentPane().add(F4sq);
		F4sq.setBounds(221,6,20,20);
		F4lbl.setRequestFocusEnabled(false);
		F4lbl.setText("F4");
		getContentPane().add(F4lbl);
		F4lbl.setForeground(java.awt.Color.black);
		F4lbl.setFont(new Font("SansSerif", Font.PLAIN, 10));
		F4lbl.setBounds(225,6,20,20);
		getContentPane().add(F9sq);
		F9sq.setBounds(283,6,20,20);
		F9lbl.setRequestFocusEnabled(false);
		F9lbl.setText("F9");
		getContentPane().add(F9lbl);
		F9lbl.setForeground(java.awt.Color.black);
		F9lbl.setFont(new Font("SansSerif", Font.PLAIN, 10));
		F9lbl.setBounds(287,6,20,20);
		getContentPane().add(F12sq);
		F12sq.setBounds(345,6,20,20);
		F12lbl.setRequestFocusEnabled(false);
		F12lbl.setText("F12");
		getContentPane().add(F12lbl);
		F12lbl.setForeground(java.awt.Color.black);
		F12lbl.setFont(new Font("SansSerif", Font.PLAIN, 10));
		F12lbl.setBounds(346,6,20,20);
		F2action.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		F2action.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		F2action.setText("Add");
		getContentPane().add(F2action);
		F2action.setForeground(java.awt.Color.black);
		F2action.setBounds(72,30,70,16);
		F3action.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		F3action.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		F3action.setText("Update");
		getContentPane().add(F3action);
		F3action.setForeground(java.awt.Color.black);
		F3action.setBounds(134,30,70,16);
		F4action.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		F4action.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		F4action.setText("Print");
		getContentPane().add(F4action);
		F4action.setForeground(java.awt.Color.black);
		F4action.setBounds(196,30,70,16);
		F9action.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		F9action.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		F9action.setText("Exit");
		getContentPane().add(F9action);
		F9action.setForeground(java.awt.Color.black);
		F9action.setBounds(258,30,70,16);
		F12action.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		F12action.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		F12action.setText("Submit");
		getContentPane().add(F12action);
		F12action.setForeground(java.awt.Color.black);
		F12action.setBounds(320,30,70,16);
		getContentPane().add(msgLabel);
		msgLabel.setForeground(java.awt.Color.red);
		msgLabel.setFont(new Font("Dialog", Font.BOLD, 12));
		msgLabel.setBounds(32,52,352,14);
		F1action.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		F1action.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		F1action.setText("Query");
		getContentPane().add(F1action);
		F1action.setForeground(java.awt.Color.black);
		F1action.setBounds(10,30,70,16);
		tissueCode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		tissueCode.setEnabled(false);
		getContentPane().add(tissueCode);
		tissueCode.setFont(new Font("DialogInput", Font.PLAIN, 12));
		tissueCode.setBounds(14,76,45,20);
		tissueCodeDesc.setEnabled(false);
		getContentPane().add(tissueCodeDesc);
		tissueCodeDesc.setFont(new Font("DialogInput", Font.PLAIN, 11));
		tissueCodeDesc.setBounds(59,76,544,20);
		activeStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		activeStatus.setEnabled(false);
		getContentPane().add(activeStatus);
		activeStatus.setFont(new Font("DialogInput", Font.PLAIN, 12));
		activeStatus.setBounds(604,76,39,20);
		rowNumber.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
		getContentPane().add(rowNumber);
		rowNumber.setForeground(java.awt.Color.black);
		rowNumber.setFont(new Font("SansSerif", Font.BOLD, 10));
		rowNumber.setBounds(14,378,100,14);
		getContentPane().add(descrLbl);
		descrLbl.setFont(new Font("SansSerif", Font.PLAIN, 10));
		descrLbl.setBounds(400,8,350,40);
		//}}
		
		dData = new TissueCodeTableData();
		tissueCodeTable = new JTable();
		tissueCodeTable.setEnabled(false);
		tissueCodeTable.setAutoCreateColumnsFromModel(false);
		tissueCodeTable.setModel(dData);

		
		for (int k=0;k<dData.columns.length;k++) {
		    DefaultTableCellRenderer renderer = new
		        DefaultTableCellRenderer();
            renderer.setHorizontalAlignment(
                dData.columns[k].alignment);
            renderer.setFont(
                dData.columns[k].font);
            TableColumn column = new TableColumn(k,
                dData.columns[k].width,renderer,null);
            tissueCodeTable.addColumn(column);
		}
		
		header = tissueCodeTable.getTableHeader();
		header.setFont(new Font("Dialog",Font.BOLD, 11));
	
		rCodeScrollPane = new JScrollPane();
		rCodeScrollPane.getViewport().add(tissueCodeTable);
		getContentPane().add(rCodeScrollPane);
		rCodeScrollPane.setBounds(10,100,650,250);
        rCodeScrollPane.setAutoscrolls(true);
        rCodeScrollPane.setEnabled(false);
		
		tissueCodeTable.setFont(new Font("SansSerif", Font.PLAIN, 10));
		tissueCodeTable.setBounds(0,0,647,247);
        tissueCodeTable.setRowHeight(12);
        tissueCodeTable.setCellSelectionEnabled(false);
        tissueCodeTable.setEnabled(false);    

		//{{INIT_MENUS
		//}}
	
		//{{REGISTER_LISTENERS
		SymKey aSymKey = new SymKey();
		tissueCode.addKeyListener(aSymKey);
		tissueCodeDesc.addKeyListener(aSymKey);
		//}}
		
		actionMap = new PcsActionMap(this);
		this.setupKeyPressMap();
	}
	protected JRootPane setupKeyPressMap() {
		JRootPane rp = super.setupKeyPressMap();
		rp.getActionMap().put("F4", new AbstractAction() {
			public void actionPerformed(ActionEvent e) {
				printResultCodes();
			}
		});
		rp.getActionMap().put("VK_DOWN", new AbstractAction() {
			public void actionPerformed(ActionEvent e) {
				if (currMode==Lab.IDLE) {
		        	int ndx;
		            increment();
                    msgLabel.setText(null);
                    if (tissueCodeTable.getSelectedRow()==(-1)) ndx=0;
		            else ndx=tissueCodeTable.getSelectedRow()+1;
                    if (ndx==resultCodeVect.size()) ndx--;
		            setEntryFields();
		        }
			}
		});
		rp.getActionMap().put("VK_UP", new AbstractAction() {
			public void actionPerformed(ActionEvent e) {
				if (currMode==Lab.IDLE) {
                	int ndx;
                    decrement();
                    msgLabel.setText(null);
                    if (tissueCodeTable.getSelectedRow()==(-1)) ndx=0;
		            else ndx=tissueCodeTable.getSelectedRow()-1;
                    if (ndx==(-1)) ndx=0;
		            setEntryFields();
		        }
			}
		});
		rp.getActionMap().put("VK_HOME", new AbstractAction() {
			public void actionPerformed(ActionEvent e) {
				 if (currMode==Lab.IDLE) {
	                    displayRow(0);
	                    msgLabel.setText(null);
			            setEntryFields();
	                }
			}
		});
		rp.getActionMap().put("VK_END", new AbstractAction() {
			public void actionPerformed(ActionEvent e) {
				 if (currMode==Lab.IDLE) {
	                    displayRow(resultCodeVect.size()-1);
	                    msgLabel.setText(null);
			            setEntryFields();
	                }
			}
		});
		rp.getActionMap().put("ESC", new AbstractAction() {
			public void actionPerformed(ActionEvent e) {
				currMode=Lab.IDLE;
                resetForm();
                displayList(0);
                setEntryFields();
			}
		});
		return rp;
	}
	public TissueCodeForm(String sTitle)
	{
		this();
		setTitle(sTitle);
	}
	
    public TissueCodeForm(Login dbLogin) {
        this();
        this.dbLogin=dbLogin;
        boolean rc = this.getResultCodes();
        this.displayList(0);
        this.resetForm();
    }

	public void setVisible(boolean b)
	{
		if (b)
			setLocation(50, 50);
		super.setVisible(b);
	}

	static public void main(String args[])
	{
		(new TissueCodeForm()).setVisible(true);
	}

	public void addNotify()
	{
		// Record the size of the window prior to calling parents addNotify.
		Dimension size = getSize();

		super.addNotify();

		if (frameSizeAdjusted)
			return;
		frameSizeAdjusted = true;

		// Adjust size of frame according to the insets and menu bar
		Insets insets = getInsets();
		javax.swing.JMenuBar menuBar = getRootPane().getJMenuBar();
		int menuBarHeight = 0;
		if (menuBar != null)
			menuBarHeight = menuBar.getPreferredSize().height;
		setSize(insets.left + insets.right + size.width, insets.top + insets.bottom + size.height + menuBarHeight);
	}

	// Used by addNotify
	boolean frameSizeAdjusted = false;

	//{{DECLARE_CONTROLS
	Square F1sq = new Square();
	javax.swing.JLabel F1lbl = new javax.swing.JLabel();
	Square F2sq = new Square();
	javax.swing.JLabel F2lbl = new javax.swing.JLabel();
	Square F3sq = new Square();
	javax.swing.JLabel F3lbl = new javax.swing.JLabel();
	Square F4sq = new Square();
	javax.swing.JLabel F4lbl = new javax.swing.JLabel();
	Square F9sq = new Square();
	javax.swing.JLabel F9lbl = new javax.swing.JLabel();
	Square F12sq = new Square();
	javax.swing.JLabel F12lbl = new javax.swing.JLabel();
	javax.swing.JLabel F2action = new javax.swing.JLabel();
	javax.swing.JLabel F3action = new javax.swing.JLabel();
	javax.swing.JLabel F4action = new javax.swing.JLabel();
	javax.swing.JLabel F9action = new javax.swing.JLabel();
	javax.swing.JLabel F12action = new javax.swing.JLabel();
	javax.swing.JLabel msgLabel = new javax.swing.JLabel();
	javax.swing.JLabel F1action = new javax.swing.JLabel();
	javax.swing.JTextField tissueCode = new javax.swing.JTextField();
	javax.swing.JTextField tissueCodeDesc = new javax.swing.JTextField();
	javax.swing.JTextField activeStatus = new javax.swing.JTextField();
	javax.swing.JLabel rowNumber = new javax.swing.JLabel();
	JLabel descrLbl = new JLabel();
	//}}

	//{{DECLARE_MENUS
	//}}

    public boolean getResultCodes()  {
        boolean exitStatus=true;
        try  {
            String query = 
                "SELECT tissue_code,description,active_status \n"+
                "FROM pcs.tissue_codes \n"+
                "ORDER BY tissue_code \n";
                
            resultCodeVect = new Vector();                
            System.out.println(query);                
            Statement stmt = dbConnection.process().createStatement();
            ResultSet rs = stmt.executeQuery(query);
            int rowsReturned=0;
            while (rs.next()) {
                ResultCodeRec r = new ResultCodeRec();
                r.tissue_code=rs.getString(1).trim();
                r.description=rs.getString(2);
                r.active_status=rs.getString(3);
                resultCodeVect.addElement(r);
            }
        }
        catch( Exception e ) {
            System.out.println(e+" getResultCodes");
            exitStatus=false;
            msgLabel.setText("Operation Failed");
        }
        return(exitStatus);            
    }
    
	public void displayTissueCodeTable()
	{
        if (dData.getRowCount()==0) {
            for (int i=0; i<resultCodeVect.size(); i++) {
                ResultCodeRec r = (ResultCodeRec)resultCodeVect.elementAt(i);
                dData.addRow(r.tissue_code,r.description,r.active_status);
            }
        }
	}

    void clearTissueCodeTable()  {
        dData.removeAllRows();
        tissueCodeTable.removeAll();
        tissueCodeTable.revalidate();
        tissueCodeTable.repaint();
    }            
    
    void displayRow(int ndx)
    {
        try { descrLbl.setText("  "); }
        catch (Exception e) { }
        tissueCodeTable.clearSelection();
        tissueCodeTable.addRowSelectionInterval(ndx,ndx);
        tissueCodeTable.scrollRectToVisible(tissueCodeTable.getCellRect(ndx,0,true));
        setEntryFields();
        ndx++;
        rowNumber.setVisible(true);
        rowNumber.setText(" "+ndx+" of "+resultCodeVect.size());
    }

	public void increment()
	{
        int ndx=tissueCodeTable.getSelectedRow();
        if (ndx<0) ndx=0;
        else if (ndx<resultCodeVect.size()-2) ndx++;
        else ndx=resultCodeVect.size()-1;
        displayRow(ndx);
	}
	
	public void decrement()
	{
        int ndx=tissueCodeTable.getSelectedRow();
        if (ndx>resultCodeVect.size()) ndx=resultCodeVect.size()-1;
        else if (ndx>1) ndx--;
        else ndx=0;
        displayRow(ndx);
	}

    public void displayList(int ndx) {
        displayTissueCodeTable();
        displayRow(ndx);
    }

	class SymKey extends java.awt.event.KeyAdapter
	{
		public void keyTyped(java.awt.event.KeyEvent event)
		{
			Object object = event.getSource();
			if (object == tissueCode)
				tissueCode_keyTyped(event);
			else if (object == tissueCodeDesc)
				tissueCodeDesc_keyTyped(event);
			else if (object == activeStatus)
				activeStatus_keyTyped(event);
		}

		public void keyPressed(java.awt.event.KeyEvent event)
		{
			Object object = event.getSource();
			if (object == activeStatus)
				activeStatus_keyPressed(event);
			else if (object == tissueCode)
				tissueCode_keyPressed(event);
			else if (object == tissueCodeDesc)
				tissueCodeDesc_keyPressed(event);
		}
	}

	
	
	public void queryActions() {
	    currMode=Lab.QUERY;
	    fKeys.off();
	    fKeys.keyOn(fKeys.F12);
	    fKeys.keyOn(fKeys.F9);
	    tissueCode.setEnabled(true);
	    tissueCode.setText(null);
	    tissueCodeDesc.setText(null);
	    activeStatus.setText(null);
	    tissueCode.requestFocus();
	}
	
	public void finalActions() {
	    if (currMode==Lab.QUERY) {
	        boolean codeFound=false;
	        for (int i=0;i<resultCodeVect.size();i++) {
	            String buf=(String)dData.getValueAt(i,0);
	            if (buf.equals(tissueCode.getText())) {
	                displayRow(i);
	                setEntryFields();
	                codeFound=true;
	                break;
	            }
	        }
	        currMode=Lab.IDLE;
	        tissueCode.setEnabled(false);
	        msgLabel.requestFocus();
	        if (codeFound==false) {
	            resetForm();
	            msgLabel.setText("Code Not Found");
	        }
            fKeys.off();
	        fKeys.keyOn(fKeys.F1);
	        fKeys.keyOn(fKeys.F2);
	        fKeys.keyOn(fKeys.F3);
	        fKeys.keyOn(fKeys.F4);
	        fKeys.keyOn(fKeys.F9);
	    }
	    else if (currMode==Lab.ADD) {
	        boolean codeExists=false;
	        for (int i=0;i<resultCodeVect.size();i++) {
	            String buf=(String)dData.getValueAt(i,0);
	            if (buf.equals(tissueCode.getText())) {
	                displayRow(i);
	                setEntryFields();
	                tissueCode.setEnabled(false);
	                tissueCodeDesc.setEnabled(false);
	                msgLabel.requestFocus();
	                msgLabel.setText("Result Code already exists");
	                codeExists=true;
	                currMode=Lab.IDLE;
	                break;
	            }
	        }
	        if (codeExists==false)  {
	            boolean rv=addResultCode();
	            if (rv) {
	                msgLabel.setText("Operation Succeeded");
	                clearTissueCodeTable();
	                getResultCodes();
	                displayTissueCodeTable();
	            }
	        }
	        tissueCode.setEnabled(false);
	        tissueCodeDesc.setEnabled(false);
	        msgLabel.requestFocus();
	        currMode=Lab.IDLE;
            fKeys.off();
	        fKeys.keyOn(fKeys.F1);
	        fKeys.keyOn(fKeys.F2);
	        fKeys.keyOn(fKeys.F3);
	        fKeys.keyOn(fKeys.F4);
	        fKeys.keyOn(fKeys.F9);
	    }
	    else if (currMode==Lab.UPDATE) {
	        String code=tissueCode.getText();
	        String desc=tissueCodeDesc.getText();
	        String status=activeStatus.getText();
	        int pClass=0;
	        boolean rv=updateResultCode(code,desc,status);
	        if (rv==true) { 
	            msgLabel.setText("Operation Succeeded");
                clearTissueCodeTable();
	            getResultCodes();
	            //displaytissueCodeTable();
	            displayList(rowID-1);
	        }
	        currMode=Lab.IDLE;
	        msgLabel.requestFocus();
	        tissueCode.setEnabled(false);
	        tissueCodeDesc.setEnabled(false);
	        activeStatus.setEnabled(false);
	        descriptionChanged=false;
            fKeys.off();
            fKeys.keyOn(fKeys.F1);
	        fKeys.keyOn(fKeys.F2);
	        fKeys.keyOn(fKeys.F3);
	        fKeys.keyOn(fKeys.F4);
	        fKeys.keyOn(fKeys.F9);
	    }
	}

	public void setEntryFields() {
	    int ndx=tissueCodeTable.getSelectedRow();
	    ResultCodeRec r = (ResultCodeRec)resultCodeVect.elementAt(ndx);
	    tissueCode.setText(r.tissue_code);
	    tissueCodeDesc.setText(r.description);
	    activeStatus.setText(r.active_status);
        try { descrLbl.setText((String)dData.getValueAt(ndx,1)); }
        catch (Exception e) { }
	}
	
	public void addActions() {
	    currMode=Lab.ADD;
	    fKeys.off();
	    fKeys.keyOn(fKeys.F12);
	    fKeys.keyOn(fKeys.F9);
	    tissueCode.setText(null);
	    tissueCodeDesc.setText(null);
	    activeStatus.setText("A");
        tissueCode.setEnabled(true);
        tissueCodeDesc.setEnabled(true);
	    tissueCode.requestFocus();
	}
	
	public boolean addResultCode() {
        boolean exitStatus=true;
        try  {
            String query = 
                "INSERT INTO pcs.tissue_codes \n"+
                "(tissue_code,description,active_status) \n"+
                "VALUES (?,?,'A') \n";
                
            System.out.println(query);                
            PreparedStatement pstmt = dbConnection.process().prepareStatement(query);
            pstmt.setString(1,tissueCode.getText());
            pstmt.setString(2,tissueCodeDesc.getText());
            int rs = pstmt.executeUpdate();
        }
        catch( Exception e ) {
            System.out.println(e+" addResultCode");
            exitStatus=false;
            msgLabel.setText("Operation Failed");
        }
        
        return(exitStatus);            
    }
    
	void resultCode_keyTyped(java.awt.event.KeyEvent event)
	{
		Utils.forceUpper(event,4);
	}

	void resultCodeDesc_keyTyped(java.awt.event.KeyEvent event)
	{
		Utils.forceUpper(event);
	}
	
	public void deleteActions() {
	    currMode=Lab.DELETE;
	    fKeys.off();
	    fKeys.keyOn(fKeys.F12);
	    fKeys.keyOn(fKeys.F9);
	    if (activeStatus.getText().compareTo("A")==0) {
	        activeStatus.setText("I");
	        msgLabel.setText("Code Inactivated - Press F12 to Finalize");
	    }
	    else {
	        activeStatus.setText("A");
	        msgLabel.setText("Code Reactivated - Press F12 to Finalize");
	    }
	}
	
	public void resetForm() {
	    resetColors();
	    try { descrLbl.setText("  "); }
	    catch (Exception e) { }
	    rowNumber.setText(null);
	    rowNumber.setVisible(false);
	    msgLabel.setText(null);
	    msgLabel.requestFocus();
	    tissueCode.setEnabled(false);
	    tissueCodeDesc.setEnabled(false);
	    activeStatus.setEnabled(false);
	    descriptionChanged=false;
	    fKeys.off();
	    fKeys.keyOn(fKeys.F1);
	    fKeys.keyOn(fKeys.F2);
	    fKeys.keyOn(fKeys.F3);
	    fKeys.keyOn(fKeys.F4);
	    fKeys.keyOn(fKeys.F9);
	}
	
	public void updateActions() {
	    currMode=Lab.UPDATE;
	    fKeys.off();
	    fKeys.keyOn(fKeys.F12);
	    fKeys.keyOn(fKeys.F9);
	    oldDescription=tissueCodeDesc.getText();
        tissueCodeDesc.setEnabled(true);
        activeStatus.setEnabled(true);
        tissueCodeDesc.requestFocus();
	}
	
	public boolean updateResultCode(String code, String desc, String status) {
        boolean exitStatus=true;
        try  {
            String SQL = 
                "UPDATE pcs.tissue_codes \n"+
                "SET \n"+
                "   description = ?, \n"+
                "   active_status = ? \n"+
                "WHERE tissue_code = ? \n";
                
            PreparedStatement pstmt = dbConnection.process().prepareStatement(SQL);
            pstmt.setString(1,desc);
            pstmt.setString(2,status);
            pstmt.setString(3,code);
            int rs = pstmt.executeUpdate();
        }
        catch( Exception e ) {
            System.out.println(e+" updateResultCode");
            exitStatus=false;
            msgLabel.setText("Operation Failed");
        }
        return(exitStatus);            
	}


	void activeStatus_keyPressed(java.awt.event.KeyEvent event)
	{
        if (event.getKeyCode()==event.VK_ENTER) {
		    activeStatus.transferFocus();
		}
	}

	void activeStatus_keyTyped(java.awt.event.KeyEvent event)
	{
		Utils.forceUpper(event,1);
	}

	void tissueCode_keyTyped(java.awt.event.KeyEvent event)
	{
		Utils.forceUpper(event,8);
	}

	void tissueCode_keyPressed(java.awt.event.KeyEvent event)
	{
		if (event.getKeyCode()==event.VK_ENTER) {
		    if (Utils.requiredField(tissueCode,"Tissue Code")) {
		        if (currMode==Lab.QUERY) finalActions();
		        else tissueCode.transferFocus();
		    }
		}
		    
	}

	void tissueCodeDesc_keyTyped(java.awt.event.KeyEvent event)
	{
        // Allow description to be all upper or mixed case
		//Utils.forceUpper(event);
	}

	void tissueCodeDesc_keyPressed(java.awt.event.KeyEvent event)
	{
		if (event.getKeyCode()==event.VK_ENTER) {
		    if (Utils.requiredField(tissueCodeDesc,"Description")) {
		        tissueCodeDesc.transferFocus();
		    }
		}
	}

	void resetColors()
	{
	    Utils.setColors(this.getContentPane());
	    descrLbl.setForeground(Color.green);
	    rowNumber.setForeground(Color.white);
	    msgLabel.setForeground(Color.green);
		descrLbl.setFont(new Font("SansSerif", Font.BOLD, 10));
		rowNumber.setFont(new Font("SansSerif", Font.BOLD, 10));
	}

	class SymFocus extends java.awt.event.FocusAdapter
	{
		public void focusGained(java.awt.event.FocusEvent event)
		{
			Object object = event.getSource();
			if (object == tissueCode)
				resultCode_focusGained(event);
			else if (object == tissueCodeDesc)
				resultCodeDesc_focusGained(event);
			else if (object == activeStatus)
				activeStatus_focusGained(event);
		}
	}

	void resultCode_focusGained(java.awt.event.FocusEvent event)
	{
		Utils.deselect(event);
		msgLabel.setText("Enter Tissue Code");
	}

	void resultCodeDesc_focusGained(java.awt.event.FocusEvent event)
	{
		Utils.deselect(event);
		msgLabel.setText("Enter Description");
	}

	void pathNeeded_focusGained(java.awt.event.FocusEvent event)
	{
		Utils.deselect(event);
		msgLabel.setText("Pathologist needed for this code (Y/N) ?");
	}

	void category_focusGained(java.awt.event.FocusEvent event)
	{
		Utils.deselect(event);
		try {
		descrLbl.setText(
		    "S = Specimen Adequacy;  G = General Categorization;  D = Description;  R = Remarks");
		}
		catch (Exception e) { }
	}

	void activeStatus_focusGained(java.awt.event.FocusEvent event)
	{
		Utils.deselect(event);
		msgLabel.setText("Enter Status, A = Active; I = Inactive");
	}

    public void printResultCodes() {
        PrintJob pjob;
        Properties p = new java.util.Properties();
        Graphics pgraphics;
        String name = new String("Tissue Codes");
        pjob=getToolkit().getPrintJob(this,name,p);
        lineCount=1; pageNumber=0;
        String buf=new String(), buf2=new String();
        if (pjob!=null) {
            x=20; y=20;
            pgraphics=pjob.getGraphics();
            for (int ndx=0; ndx<resultCodeVect.size(); ndx++) {
                ResultCodeRec r = (ResultCodeRec)resultCodeVect.elementAt(ndx);
                if (ndx==0) {
                    if (pgraphics!=null) printHeader(pgraphics);
                }
                if (pgraphics!=null) {
                    pgraphics.setFont(new Font("MonoSpaced",Font.PLAIN,10));
                    y+=12;
                    lineCount++;
                    if (lineCount>60) {
                        pgraphics.dispose();
                        pgraphics=pjob.getGraphics();
                        if (pgraphics!=null) printHeader(pgraphics);
                    }
                    pgraphics.drawString("CODE:  "+r.tissue_code,x,y);
                    x=350;
                    pgraphics.drawString("STATUS:  "+r.active_status,x,y);
                    x=20; y+=12; lineCount++;
                    if (lineCount>60) {
                        pgraphics.dispose();
                        pgraphics=pjob.getGraphics();
                        if (pgraphics!=null) printHeader(pgraphics);
                    }
                    pgraphics.drawString("CATEGORY:  "+r.category,x,y);
                    x=350;
                    pgraphics.drawString("CLASS:  "+Integer.toString(r.pap_class),x,y);
                    x=20; y+=12; lineCount++;
                    if (lineCount>60) {
                        pgraphics.dispose();
                        pgraphics=pjob.getGraphics();
                        if (pgraphics!=null) printHeader(pgraphics);
                    }
                    pgraphics.drawString("PATHOLOGIST:  "+r.path_needed,x,y);
                    x=350;
                    pgraphics.drawString("BX:  "+r.biopsy_request,x,y);
                    x=20; y+=12; lineCount++;
                    if (lineCount>60) {
                        pgraphics.dispose();
                        pgraphics=pjob.getGraphics();
                        if (pgraphics!=null) printHeader(pgraphics);
                    }
                    x=20; y+=12; lineCount+=1;
                    buf = new String(r.description);
                    if (Utils.length(buf)>90) {
                        buf2 = new String(buf);
                        int endNdx=0;
                        while (Utils.length(buf2)>90) {
                            for (int k=0;k<90;k++) {
                                if (buf2.charAt(k)==' ')
                                endNdx=k;
                            }
                            buf = new String(buf2.substring(0,endNdx));
                            buf2 = new String(buf2.substring(endNdx).trim());
                            pgraphics.drawString(buf,x,y);
                            y+=12; lineCount++;
                            if (lineCount>60) {
                                pgraphics.dispose();
                                pgraphics=pjob.getGraphics();
                                if (pgraphics!=null) printHeader(pgraphics);
                            }
                        }
                        if (!Utils.isNull(buf2)) {
                            pgraphics.drawString(buf2,x,y);
                            y+=12; lineCount++;
                            if (lineCount>60) {
                                pgraphics.dispose();
                                pgraphics=pjob.getGraphics();
                                if (pgraphics!=null) printHeader(pgraphics);
                            }
                        }
                    }
                    else {
                        pgraphics.drawString(buf,x,y);
                        y+=12; lineCount++;
                        if (lineCount>60) {
                            pgraphics.dispose();
                            pgraphics=pjob.getGraphics();
                            if (pgraphics!=null) printHeader(pgraphics);
                        }
                    }
                    for (int j=0; j<r.beth_prior_descr.size(); j++) {
                        BethPriorDescr t =
                            (BethPriorDescr)r.beth_prior_descr.elementAt(j);
                        x=20; y+=12;
                        pgraphics.drawString("TERMINATED: "+t.term_date,x,y);
                        y+=12; lineCount++;
                        if (lineCount>60) {
                            pgraphics.dispose();
                            pgraphics=pjob.getGraphics();
                            if (pgraphics!=null) printHeader(pgraphics);
                        }
                        buf = new String(t.description);
                        if (Utils.length(buf)>90) {
                            buf2 = new String(buf);
                            int endNdx=0;
                            while (Utils.length(buf2)>90) {
                                for (int k=0;k<90;k++) {
                                    if (buf2.charAt(k)==' ')
                                    endNdx=k;
                                }
                                buf = new String(buf2.substring(0,endNdx));
                                buf2 = new String(buf2.substring(endNdx).trim());
                                pgraphics.drawString(buf,x,y);
                                y+=12; lineCount++;
                                if (lineCount>60) {
                                    pgraphics.dispose();
                                    pgraphics=pjob.getGraphics();
                                    if (pgraphics!=null) printHeader(pgraphics);
                                }
                            }
                            if (!Utils.isNull(buf2)) {
                                pgraphics.drawString(buf2,x,y);
                                y+=12; lineCount++;
                                if (lineCount>60) {
                                    pgraphics.dispose();
                                    pgraphics=pjob.getGraphics();
                                    if (pgraphics!=null) printHeader(pgraphics);
                                }
                            }
                        }
                        else {
                            pgraphics.drawString(buf,x,y);
                            y+=12; lineCount++;
                            if (lineCount>60) {
                                pgraphics.dispose();
                                pgraphics=pjob.getGraphics();
                                if (pgraphics!=null) printHeader(pgraphics);
                            }
                        }
                    }
                    pgraphics.drawString(
                        "-----------------------------"+
                        "-----------------------------"+
                        "-----------------------------",x,y);
                    x=20; y+=12; lineCount++;
                    if (lineCount>60) {
                        pgraphics.dispose();
                        pgraphics=pjob.getGraphics();
                        if (pgraphics!=null) printHeader(pgraphics);
                    }
                }
            }
        }       
        pjob.end();
    }
    
    private void printHeader(Graphics pgraphics)
    {
        y=20; lineCount=1; pageNumber++;
        pgraphics.setFont(new Font("MonoSpaced",Font.BOLD,10));
        y+=12; lineCount+=1;
        pgraphics.drawString("PENNSYLVANIA CYTOLOGY SERVICES",x,y);
        y+=12; lineCount+=1;
        pgraphics.drawString("TISSUE CODES REPORT",x,y);
        y+=12; lineCount+=1;
        pgraphics.drawString("Page "+Integer.toString(pageNumber),x,y);
        pgraphics.drawString("    ",x,y);
        y+=24; lineCount+=2;
        pgraphics.setFont(new Font("MonoSpaced",Font.PLAIN,10));
    }
	

}
